/**@file
 * Clock tree support library — flyweight architecture.
 *
 * Provides the generic clock tree framework. Per-chip clock tree data is
 * generated by sodaCat and stored as constexpr descriptor tables.
 */
#pragma once

#ifndef EXPORT
#define EXPORT
#endif

#include <cstdint>
#include <span>

namespace clocktree {

class ClockTreeBase;

/// Frequency computation function signature.
/// @param desc     Pointer to the element's descriptor (type-specific)
/// @param inputs   Pointer into the input pool (signal IDs of this element's inputs)
/// @param tree     The clock tree instance (for recursive getFrequency and mutable state)
using FreqFn = uint32_t(*)(void const* desc, uint8_t const* inputs, ClockTreeBase const& tree);

/// Block type descriptor — one entry per distinct element type in the type table.
struct BlockType {
    FreqFn       freq;          ///< Frequency computation function
    void const*  descriptors;   ///< Pointer to constexpr descriptor array
    uint8_t      desc_size;     ///< sizeof(one descriptor), for pointer arithmetic
};

/// Signal-to-element mapping — 4 bytes per signal.
struct Signal {
    uint8_t  type;          ///< Index into the type table (0 = undriven)
    uint8_t  desc_index;    ///< Index into that type's descriptor array
    uint16_t input_offset;  ///< Offset into the input pool
};

// ---------------------------------------------------------------------------
// Helpers for reading MMIO bitfields from packed addresses
// ---------------------------------------------------------------------------

/// Base address of the Cortex-M peripheral region.
/// Word offsets in BitAddr/FieldAddr are relative to this.
inline constexpr uintptr_t periph_base = 0x40000000;

/// Read a single bit from an MMIO register.
/// @param word_offset  Register word offset from periph_base
/// @param bit          Bit position within the 32-bit register
inline uint32_t read_bit(uint32_t word_offset, uint32_t bit) {
    auto reg = *reinterpret_cast<volatile uint32_t const*>(periph_base + (uintptr_t(word_offset) << 2));
    return (reg >> bit) & 1;
}

/// Read a multi-bit field from an MMIO register.
/// @param word_offset  Register word offset from periph_base
/// @param bit          Bit position of the LSB
/// @param width        Field width in bits
inline uint32_t read_field(uint32_t word_offset, uint32_t bit, uint32_t width) {
    auto reg = *reinterpret_cast<volatile uint32_t const*>(periph_base + (uintptr_t(word_offset) << 2));
    return (reg >> bit) & ((1u << width) - 1);
}

// ---------------------------------------------------------------------------
// Packed bit address — fits a peripheral register bit in 4 bytes.
// Covers the Cortex-M peripheral range 0x40000000–0x5FFFFFFF.
// Word offsets are relative to 0x40000000, so 27 bits cover 512 MB.
// ---------------------------------------------------------------------------

/// Packed register bit address (4 bytes).
struct BitAddr {
    uint32_t word_offset : 27;  ///< Word offset from periph_base ((byte_addr - 0x40000000) >> 2)
    uint32_t bit         : 5;   ///< Bit position within the register
};

/// Packed register bitfield address (4 bytes + width).
struct FieldAddr {
    uint32_t word_offset : 27;
    uint32_t bit         : 5;
    uint8_t  width;             ///< Field width in bits
};

// ---------------------------------------------------------------------------
// Standard descriptor types
// ---------------------------------------------------------------------------

/// Gate: passes input through when enable bit is set (4 bytes).
struct GateDesc {
    BitAddr addr;
};

/// Inverted gate: passes input through when enable bit is clear (4 bytes).
/// Uses the same struct as GateDesc but a different frequency function.
using GateInvDesc = GateDesc;

/// Generator with a fixed frequency (8 bytes).
struct GenFixedDesc {
    BitAddr  addr;              ///< Enable bit
    uint32_t frequency;         ///< Nominal frequency in Hz
};

/// Generator with runtime-configurable frequency, e.g. external oscillator (5 bytes).
struct GenExternalDesc {
    BitAddr addr;               ///< Enable bit
    uint8_t state_slot;         ///< Index into the mutable state[] array
};

/// Divider with table-based divisor lookup (8 bytes).
struct TableDivDesc {
    FieldAddr field;            ///< Register field selecting the divisor
    uint8_t   table_offset;     ///< Offset into shared value_tables pool
    uint8_t   table_size;       ///< Number of entries in the table
};

/// Divider with linear divisor: divisor = raw_field + offset (6 bytes).
struct LinearDivDesc {
    FieldAddr field;
    uint8_t   offset;           ///< Added to raw field value
};

/// Fixed divider: always divides by a constant (2 bytes).
struct FixedDivDesc {
    uint16_t divisor;
};

/// Multiplexer: selects one of N input signals (6 bytes).
struct MuxDesc {
    FieldAddr field;            ///< Register field containing selector value
    uint8_t   input_count;      ///< Number of selectable inputs
};

/// PLL: output = input * (fb_int + fb_frac / 2^frac_bits) / post_div.
struct PllDesc {
    FieldAddr fb_int;           ///< Feedback integer (DIVN etc.)
    uint8_t   fb_int_offset;    ///< Added to raw value (typically 1)
    FieldAddr fb_frac;          ///< Feedback fraction (FRACN etc.), width=0 means unused
    uint8_t   frac_bits;        ///< Number of fractional bits (e.g. 13)
    FieldAddr post_div;         ///< Post-divider, width=0 means unused (factor = 1)
    uint8_t   post_div_offset;  ///< Added to raw value (typically 1)
};

// ---------------------------------------------------------------------------
// Standard frequency functions
// ---------------------------------------------------------------------------

/// Gate: output = input if enable bit is set, else 0.
inline uint32_t gate_freq(void const* desc, uint8_t const* inputs, ClockTreeBase const& tree);

/// Inverted gate: output = input if enable bit is clear, else 0.
inline uint32_t gate_inv_freq(void const* desc, uint8_t const* inputs, ClockTreeBase const& tree);

/// Unconditional pass-through (gate without control bit).
inline uint32_t passthrough_freq(void const* desc, uint8_t const* inputs, ClockTreeBase const& tree);

/// Generator with fixed frequency.
inline uint32_t gen_fixed_freq(void const* desc, uint8_t const* inputs, ClockTreeBase const& tree);

/// Generator with external (runtime) frequency.
inline uint32_t gen_external_freq(void const* desc, uint8_t const* inputs, ClockTreeBase const& tree);

/// Divider with table lookup.
inline uint32_t table_div_freq(void const* desc, uint8_t const* inputs, ClockTreeBase const& tree);

/// Divider with linear formula: divisor = raw + offset.
inline uint32_t linear_div_freq(void const* desc, uint8_t const* inputs, ClockTreeBase const& tree);

/// Fixed divider: always divides by a constant.
inline uint32_t fixed_div_freq(void const* desc, uint8_t const* inputs, ClockTreeBase const& tree);

/// Multiplexer: selects one input based on register field.
inline uint32_t mux_freq(void const* desc, uint8_t const* inputs, ClockTreeBase const& tree);

/// PLL: output = input * (N + frac) / post_div.
inline uint32_t pll_freq(void const* desc, uint8_t const* inputs, ClockTreeBase const& tree);

// ---------------------------------------------------------------------------
// ClockTreeBase — the generic clock tree interpreter
// ---------------------------------------------------------------------------

/** Generic clock tree base class.
 *
 * Subclassed by the generated per-chip Clocks struct, which provides the
 * constexpr data tables. ClockTree<Clocks> then inherits from this and
 * exposes the public API.
 */
EXPORT class ClockTreeBase {
public:
    /// Get frequency of given signal in Hz. Returns 0 for disabled/unknown signals.
    uint32_t getFrequency(uint8_t sig_id) const {
        if (sig_id == 0 || sig_id >= signal_count) [[unlikely]]
            return 0;
        auto& s = signals[sig_id];
        if (s.type == 0) [[unlikely]]
            return 0;
        auto& t = types[s.type];
        auto desc = static_cast<uint8_t const*>(t.descriptors) + s.desc_index * t.desc_size;
        return t.freq(desc, &input_pool[s.input_offset], *this);
    }

protected:
    // These are set by the generated per-chip Clocks struct's constructor
    // or initialized via aggregate initialization.
    Signal const*    signals;
    uint16_t         signal_count;
    BlockType const* types;
    uint8_t const*   input_pool;

public:
    // Accessible by frequency functions for table lookups and mutable state
    uint32_t const*  value_tables;
    uint32_t*        state;
};

// ---------------------------------------------------------------------------
// ClockTree — the public-facing template
// ---------------------------------------------------------------------------

/** ClockTree class template, parameterized with the generated Clocks struct. */
EXPORT template<typename Clocks> class ClockTree : public Clocks {
public:
    using S = typename Clocks::S;

    template<typename... Args>
    ClockTree(Args&&... args) : Clocks(std::forward<Args>(args)...) {}

    uint32_t getFrequency(S s) const {
        return ClockTreeBase::getFrequency(static_cast<uint8_t>(s));
    }
};

// ---------------------------------------------------------------------------
// Frequency function implementations
// ---------------------------------------------------------------------------

inline uint32_t gate_freq(void const* desc, uint8_t const* inputs, ClockTreeBase const& tree) {
    auto& g = *static_cast<GateDesc const*>(desc);
    return read_bit(g.addr.word_offset, g.addr.bit)
        ? tree.getFrequency(inputs[0]) : 0;
}

inline uint32_t gate_inv_freq(void const* desc, uint8_t const* inputs, ClockTreeBase const& tree) {
    auto& g = *static_cast<GateInvDesc const*>(desc);
    return read_bit(g.addr.word_offset, g.addr.bit)
        ? 0 : tree.getFrequency(inputs[0]);
}

inline uint32_t passthrough_freq(void const* desc, uint8_t const* inputs, ClockTreeBase const& tree) {
    return tree.getFrequency(inputs[0]);
}

inline uint32_t gen_fixed_freq(void const* desc, uint8_t const* inputs, ClockTreeBase const& tree) {
    auto& g = *static_cast<GenFixedDesc const*>(desc);
    return read_bit(g.addr.word_offset, g.addr.bit) ? g.frequency : 0;
}

inline uint32_t gen_external_freq(void const* desc, uint8_t const* inputs, ClockTreeBase const& tree) {
    auto& g = *static_cast<GenExternalDesc const*>(desc);
    return read_bit(g.addr.word_offset, g.addr.bit) ? tree.state[g.state_slot] : 0;
}

inline uint32_t table_div_freq(void const* desc, uint8_t const* inputs, ClockTreeBase const& tree) {
    auto& d = *static_cast<TableDivDesc const*>(desc);
    uint32_t raw = read_field(d.field.word_offset, d.field.bit, d.field.width);
    uint32_t divisor = raw < d.table_size ? tree.value_tables[d.table_offset + raw] : 0;
    if (!divisor) return 0;
    uint64_t in_freq = tree.getFrequency(inputs[0]);
    return uint32_t(in_freq / divisor);
}

inline uint32_t linear_div_freq(void const* desc, uint8_t const* inputs, ClockTreeBase const& tree) {
    auto& d = *static_cast<LinearDivDesc const*>(desc);
    uint32_t raw = read_field(d.field.word_offset, d.field.bit, d.field.width);
    uint32_t divisor = raw + d.offset;
    if (!divisor) return 0;
    uint64_t in_freq = tree.getFrequency(inputs[0]);
    return uint32_t(in_freq / divisor);
}

inline uint32_t fixed_div_freq(void const* desc, uint8_t const* inputs, ClockTreeBase const& tree) {
    auto& d = *static_cast<FixedDivDesc const*>(desc);
    if (!d.divisor) return 0;
    uint64_t in_freq = tree.getFrequency(inputs[0]);
    return uint32_t(in_freq / d.divisor);
}

inline uint32_t mux_freq(void const* desc, uint8_t const* inputs, ClockTreeBase const& tree) {
    auto& m = *static_cast<MuxDesc const*>(desc);
    uint32_t sel = read_field(m.field.word_offset, m.field.bit, m.field.width);
    if (sel >= m.input_count) [[unlikely]]
        return 0;
    return tree.getFrequency(inputs[sel]);
}

inline uint32_t pll_freq(void const* desc, uint8_t const* inputs, ClockTreeBase const& tree) {
    auto& p = *static_cast<PllDesc const*>(desc);
    uint32_t in_freq = tree.getFrequency(inputs[0]);
    if (!in_freq) return 0;

    uint64_t fb_int = read_field(p.fb_int.word_offset, p.fb_int.bit, p.fb_int.width) + p.fb_int_offset;
    uint64_t fb_frac = p.fb_frac.width
        ? read_field(p.fb_frac.word_offset, p.fb_frac.bit, p.fb_frac.width) : 0;

    // output = input * (fb_int + fb_frac / 2^frac_bits) / post_div
    //        = input * (fb_int << frac_bits + fb_frac) / (post_div << frac_bits)
    uint64_t numerator = (fb_int << p.frac_bits) + fb_frac;

    uint64_t post_div = p.post_div.width
        ? read_field(p.post_div.word_offset, p.post_div.bit, p.post_div.width) + p.post_div_offset : 1;
    if (!post_div) return 0;

    uint64_t denominator = post_div << p.frac_bits;
    return uint32_t(uint64_t(in_freq) * numerator / denominator);
}

} // namespace clocktree

#undef EXPORT
